### PR TITLE
ci: added github actions to enforce test, build and lint all PRs.

### LINKED ISSUE #47: [ Bounty ] Enable github actions to enforce tests, build, and linting on all PRs
# Background 
Currently the SDK has linting and tests that are functional, but we need to enforce these into our Pull Requests to enable simpler merging and QA.

# Acceptance Criteria
Add github actions to:
- Compile a production build
- Run the linter
- Run all tests

# Bounty Payout
ElasticSwap will compensate a bounty hunter 20 TIC to set this up and work with a core dev to ensure it is fully functional in our repo.

### PR DESCRIPTION
**Pull request by zhyd1997**
Resolves #47

### CODE REVIEW

**Comment by zhyd1997** [comment]
Hi @0xean 

This PR needs your code review if you have time.

**Comment by 0xean** [comment]
@zhyd1997  - apologies! I just saw this for the first time today.  will review tomorrow.

**Comment by zhyd1997** [comment]
@0xean great thanks 👍

**Review by 0xean — APPROVED** [review]
Going to merge this and test it out! Thank you!

**Comment by 0xean** [comment]
@zhyd1997 - happy to get this paid out, can you contact me in our discord?

Also if you want to work on the next step - https://github.com/ElasticSwap/elasticswap-sdk/pull/49 - happy to add some additional TIC to get this resolved.

**Comment by zhyd1997** [comment]
I will contact you on Discord

**Pull request merged**
