### PR TITLE
fix: failing eslint and prettier checks

### PR DESCRIPTION
**Pull request by 0xean**
testing github actions

### CODE REVIEW

**Comment by 0xean** [comment]
Currently this fails due to using `assert` statements in imports and this not being supported by eslint

```
$ npx eslint src/*.mjs src/**/*.mjs test/**/*.mjs test/**/*.js --fix

/Users/x/elasticswap/elasticswap-sdk/src/ErrorHandling.mjs
  1:50  error  Parsing error: Unexpected token assert

/Users/x/elasticswap/elasticswap-sdk/src/exchange/Exchange.mjs
  1:108  error  Parsing error: Unexpected token assert

/Users/x/elasticswap/elasticswap-sdk/src/exchange/ExchangeFactory.mjs
  4:129  error  Parsing error: Unexpected token assert

/Users/x/elasticswap/elasticswap-sdk/src/index.mjs
  4:121  error  Parsing error: Unexpected token assert

/Users/x/elasticswap/elasticswap-sdk/src/staking/StakingPools.mjs
  1:61  error  Parsing error: Unexpected token assert

/Users/x/elasticswap/elasticswap-sdk/src/tokens/ERC20.mjs
  1:121  error  Parsing error: Unexpected token assert
```

These assertions are enforce by the LTS version of node

```

TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "/elasticswap/elasticswap-sdk/node_modules/@elasticswap/elasticswap/artifacts/@openzeppelin/contracts/token/ERC20/ERC20.sol/ERC20.json" needs an import assertion of type "json"
    at new NodeError (node:internal/errors:371:5)
    at validateAssertions (node:internal/modules/esm/assert:82:15)
    at defaultLoad (node:internal/modules/esm/load:24:3)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:81:21)
    at async Promise.all (index 1)
    at async link (node:internal/modules/esm/module_job:86:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this 
```
It looks like babel may be an option to solve this per https://github.com/eslint/eslint/discussions/15305

Creating a bounty to resolve these issue and get it all working with out new CI actions

**Comment by zhyd1997** [comment]
@0xean 

Try this solution: 
```shell
yarn add -D @babel/eslint-parser @babel/plugin-syntax-import-assertions
```

and add these lines of code into `.eslintrc.js` file:
```js

  parser: "@babel/eslint-parser",
  parserOptions: {
    ecmaVersion: 2019,
    sourceType: 'module',
    requireConfigFile: false,
    babelOptions: {
      plugins: [
        '@babel/plugin-syntax-import-assertions'
      ],
    },
  },
```

@babel/plugin-syntax-import-assertions

**Comment by 0xean** [comment]
@zhyd1997 - attempting now!

**Comment by zhyd1997** [comment]
After added eslint plugin on `.eslintrc.js`, just run `yarn prettier:fix` and `yarn lint:fix`, and then it will work.

**Pull request merged**
